name: On-Demand APK Generation

on:
  workflow_dispatch:
    inputs:
      increment_version:
        description: "Specify version increment (patch, minor, major)"
        required: false

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Use Secret
        run: echo "My secret is ${{ secrets.MY_SECRET }}"
